// One curated fact per index per category. Picked by day-of-year, so each
// list cycles through before repeating.
const HEALTH_FACTS = [
  "The clitoris has over 8,000 nerve endings — roughly double the number in the tip of the penis.",
  "Heart attack symptoms in women often look different than in men: nausea, jaw pain, and fatigue are more common than classic chest-clutching pain.",
  "Endometriosis affects roughly 1 in 10 women of reproductive age, yet it takes an average of 7-10 years to get diagnosed.",
  "The first FDA-approved birth control pill, Enovid, was approved in 1960 — but it wasn't legal for unmarried women in every U.S. state until 1972.",
  "Elizabeth Blackwell became the first woman to earn a medical degree in the U.S. in 1849, after being rejected by nearly every other school.",
  "A person's uterus can nearly double in surface area during pregnancy, expanding from the size of a fist to the size of a watermelon.",
  "Women metabolize alcohol differently than men — lower levels of the enzyme alcohol dehydrogenase means the same drink hits harder, pound for pound.",
  "The average menstrual cycle is often taught as 28 days, but healthy cycles can range from 21 to 35 days.",
  "PCOS (polycystic ovary syndrome) affects up to 1 in 10 women of childbearing age and is one of the leading causes of infertility.",
  "Osteoporosis is four times more common in women than men, largely due to the bone density drop after menopause.",
  "The HPV vaccine can prevent over 90% of HPV-related cancers, including most cervical cancers.",
  "Autoimmune diseases like lupus and Hashimoto's thyroiditis affect women at roughly 4x the rate of men.",
  "Postpartum depression affects about 1 in 7 new mothers, but is treatable and often underreported.",
  "The uterus is the strongest muscle in the human body relative to its size, capable of exerting significant force during labor.",
  "Migraines are three times more common in women than men, largely linked to estrogen fluctuations.",
  "Rebecca Lee Crumpler became the first Black woman to earn an M.D. in the U.S. in 1864.",
  "Many clinical drug trials didn't require female participants until a 1993 NIH policy change — meaning decades of dosing data skewed male.",
  "The average person uses roughly 11,000 tampons or pads in their lifetime.",
  "Preeclampsia affects about 5-8% of pregnancies and is a leading cause of maternal and infant complications worldwide.",
  "Women are twice as likely as men to be diagnosed with depression, though biological and social factors both play a role.",
  "The cervix changes position and firmness throughout the menstrual cycle — a sign fertility awareness methods track closely.",
  "Breast tissue continues developing until about age 25, later than most other body tissue.",
  "Toxic shock syndrome, while rare, is linked to prolonged tampon use — changing every 4-8 hours reduces risk significantly.",
  "The World Health Organization didn't classify infertility as a disease (not just a personal issue) until 2009.",
  "A woman's risk of heart disease rises sharply after menopause, when protective estrogen levels drop.",
  "Gestational diabetes affects roughly 2-10% of pregnancies in the U.S. and usually resolves after birth.",
  "Pelvic floor physical therapy is an effective, evidence-based treatment for postpartum incontinence — not something to just 'live with.'",
  "The ovaries release about 300-400 eggs total across a lifetime, out of roughly 1-2 million present at birth.",
  "Iron-deficiency anemia is more common in women due to menstrual blood loss, especially with heavier cycles.",
  "The term 'hysteria' comes from the Greek word for uterus — a diagnosis historically (and wrongly) used to dismiss women's symptoms.",
  "Fibroids, benign uterine tumors, affect up to 80% of women by age 50, though many never cause symptoms.",
  "Breastfeeding triggers oxytocin release, which helps the uterus contract back to its pre-pregnancy size.",
  "Women are diagnosed with autoimmune thyroid disease about 5-8 times more often than men.",
  "The APGAR score, used to assess newborn health at birth, was invented by anesthesiologist Dr. Virginia Apgar in 1952.",
  "Vaginal pH is naturally acidic (around 3.8-4.5) to help protect against harmful bacteria.",
  "Chronic pelvic pain affects an estimated 1 in 7 women, and endometriosis or adenomyosis are common underlying causes.",
  "Progesterone rises after ovulation and is the reason body temperature ticks up slightly in the second half of the cycle.",
  "The first cervical cancer screening (Pap smear) was developed by Dr. Georgios Papanikolaou in the 1920s-40s.",
  "Perimenopause, the transition before menopause, can last anywhere from a few months to over a decade.",
  "Women are underdiagnosed for ADHD compared to men, partly because symptoms often present as inattentiveness rather than hyperactivity.",
  "The IUD, one of the most effective forms of reversible birth control, has a failure rate of less than 1%.",
  "Breast cancer risk roughly doubles for someone with a first-degree relative (mother, sister, daughter) who had it.",
  "Bacterial vaginosis, not a yeast infection, is actually the most common vaginal condition in women of reproductive age.",
  "Placenta accreta, where the placenta grows too deeply into the uterine wall, has become more common as C-section rates have risen.",
  "The luteal phase (after ovulation, before your period) is fairly fixed at about 12-14 days, while the follicular phase varies more.",
  "Vulvodynia, chronic vulvar pain without a clear cause, affects an estimated 8-16% of women at some point.",
  "Anti-Müllerian hormone (AMH) levels are used to estimate ovarian reserve, though they don't predict fertility with certainty.",
  "Women's pain is statistically more likely to be dismissed or under-treated in ERs compared to men reporting the same symptoms.",
  "Thelarche (breast development) and pubarche (pubic hair growth) don't always start at the same time during puberty.",
  "The Dalkon Shield IUD scandal of the 1970s led to major reforms in how contraceptive devices are tested and regulated.",
  "Roughly 1 in 4 women will experience a miscarriage at some point, most within the first trimester.",
  "The 'female athlete triad' links low energy availability, menstrual dysfunction, and low bone density in active women.",
  "Cervical mucus changes texture across the cycle — from dry, to sticky, to a fertile 'egg white' consistency near ovulation.",
  "Uterine adenomyosis, where endometrial tissue grows into the uterine muscle wall, can cause heavy, painful periods and is often confused with fibroids.",
  "Women are twice as likely as men to develop irritable bowel syndrome (IBS), possibly linked to hormonal fluctuations.",
  "The Guttmacher Institute tracks reproductive health policy and research — a key resource for evidence-based advocacy.",
  "Prolactin, the hormone responsible for milk production, can also suppress ovulation, which is why breastfeeding can (but doesn't always) delay fertility return.",
  "Vaginal microbiome research is a growing field — a lactobacillus-dominant flora is linked to lower risk of infections and preterm birth.",
  "The female reproductive system was historically excluded from many anatomy textbooks' 'default' diagrams well into the 20th century.",
  "Chronic stress can disrupt the hypothalamic-pituitary-ovarian axis, sometimes causing irregular or missed periods.",
  "Nurse-midwifery in the U.S. traces back to the 1920s Frontier Nursing Service, which dramatically cut maternal mortality in rural Appalachia.",
  "Ovarian torsion, when an ovary twists on its supporting ligaments, is a surgical emergency that can happen at any age.",
  "The 'placebo pill' week in combination birth control packs isn't medically necessary — it exists partly for historical/cultural acceptance reasons.",
  "Women's bones typically finish growing earlier than men's, contributing to average height differences.",
  "Interstitial cystitis, a chronic bladder condition causing pelvic pain and urgency, affects women at far higher rates than men.",
  "Colostrum, the first milk produced after birth, is packed with antibodies and often called a baby's 'first vaccine.'",
  "The postpartum period is sometimes called the 'fourth trimester,' recognizing the 12 weeks after birth as a distinct recovery phase.",
  "Estrogen has protective cardiovascular effects, which is part of why heart disease risk in women climbs after menopause.",
  "Turner syndrome, a chromosomal condition affecting about 1 in 2,000-2,500 female births, often causes short stature and ovarian insufficiency.",
  "The 'bikini medicine' problem describes how female-specific research often stops at reproductive organs, ignoring sex differences elsewhere in the body.",
  "Group B Streptococcus screening during pregnancy (35-37 weeks) helps prevent a serious newborn infection during delivery.",
  "Women are more likely than men to experience adverse drug reactions, partly due to historical underrepresentation in dosing trials.",
  "The average age of menopause in the U.S. is 51, though it's considered normal anywhere from 45 to 55.",
  "Ectopic pregnancy, when a fertilized egg implants outside the uterus, occurs in roughly 1-2% of pregnancies and is a medical emergency.",
  "Dysmenorrhea (painful periods) is one of the most common gynecological complaints, yet remains under-studied relative to how common it is.",
  "The Nurses' Health Study, started in 1976, remains one of the largest and longest-running investigations into women's health risk factors.",
  "Vasomotor symptoms like hot flashes affect up to 80% of women during the menopause transition.",
  "A retroverted ('tilted') uterus occurs in about 1 in 5 women and is a normal anatomical variation, not a disorder.",
  "Postpartum hemorrhage remains one of the leading causes of maternal mortality worldwide, but is often preventable with timely care.",
  "Cervical length shortening is monitored in high-risk pregnancies as a predictor of preterm birth risk.",
  "The 'sandwich generation' effect — caring for children and aging parents simultaneously — disproportionately falls on women and affects their own healthcare follow-through.",
  "Ovulation, not menstruation, is when estrogen typically peaks in the menstrual cycle.",
  "Uterine septum, a congenital condition where tissue divides the uterine cavity, is one of the more common causes of recurrent miscarriage.",
  "Women are diagnosed with multiple sclerosis 2-3 times more often than men, though the reasons remain an active research area.",
  "Kegel exercises, named after Dr. Arnold Kegel who popularized them in 1948, strengthen the pelvic floor muscles.",
  "The maternal mortality rate in the U.S. is higher than in most other high-income countries, with stark racial disparities within that data.",
  "Anovulatory cycles (cycles without ovulation) can still produce a period-like bleed, which is why 'having a period' doesn't always confirm ovulation happened.",
  "PMDD (premenstrual dysphoric disorder) is a severe form of PMS affecting 3-8% of menstruating people, marked by significant mood symptoms.",
  "The 'gender pain gap' in medicine describes documented patterns where women's reported pain is taken less seriously by clinicians than men's.",
  "Doulas — non-medical labor support — are linked in multiple studies to shorter labors and lower rates of C-section and intervention.",
  "Molar pregnancy, a rare complication where abnormal tissue grows instead of a viable embryo, occurs in about 1 in 1,000 U.S. pregnancies.",
  "Basal body temperature tracking works because progesterone raises core temperature by about 0.5-1°F after ovulation.",
  "Chronic yeast infections (4+ per year) affect roughly 5-8% of women and sometimes point to an underlying condition like diabetes.",
  "The 'weathering hypothesis' suggests chronic stress from systemic racism contributes to worse maternal health outcomes for Black women, independent of income or education.",
  "Ovarian cysts are extremely common and usually resolve on their own within a couple of menstrual cycles.",
  "Uterine fibroid embolization, a minimally invasive alternative to hysterectomy, was first used to treat fibroids in the 1990s.",
  "Sex-specific differences in liver enzyme activity mean some medications — like certain sleep aids — are metabolized more slowly in women, leading to updated FDA dosing guidance.",
  "The first physician assistant program was founded in 1965 at Duke University, initially training former military medics.",
  "Placenta previa, where the placenta covers the cervix, is found in about 1 in 200 pregnancies and usually requires a C-section.",
  "Follicular fluid analysis and egg freezing technology have advanced rapidly since the first successful frozen-egg birth in 1986.",
  "Women are hospitalized for autoimmune flares more often during times of hormonal shift, like postpartum and perimenopause.",
  "The 'orgasm gap' in heterosexual relationships is well-documented in research and tied partly to gaps in anatomical education.",
  "Amenorrhea (absence of periods) for 3+ months outside of pregnancy or menopause always warrants a medical workup.",
  "Uterine prolapse, where the uterus descends into the vaginal canal, affects up to half of women who've given birth to some degree, though many are asymptomatic.",
  "The first successful IVF birth, Louise Brown, was born in 1978 — a milestone that transformed reproductive medicine.",
  "Sex hormones influence immune response strength, part of why women often mount stronger vaccine responses than men — alongside more autoimmune risk.",
  "Adequate iron and folate intake before conception significantly reduces the risk of neural tube defects.",
  "The average PA program is about 27 months, and PAs can practice across nearly every medical specialty, including OB/GYN.",
];

const DISNEY_FACTS = [
  "Walt Disney was afraid of mice in real life, despite creating Mickey Mouse.",
  "Mickey Mouse was originally going to be named 'Mortimer' before Walt's wife suggested 'Mickey' instead.",
  "Snow White and the Seven Dwarfs (1937) was the first full-length hand-drawn animated feature film in movie history.",
  "Walt Disney won 22 competitive Academy Awards during his lifetime — more than anyone else ever.",
  "Disneyland in Anaheim, California opened on July 17, 1955.",
  "Cinderella Castle at Walt Disney World is actually shorter than Disneyland's Sleeping Beauty Castle — forced perspective makes it look taller.",
  "Walt Disney voiced Mickey Mouse himself from 1928 to 1947.",
  "'It's a Small World' was originally created for the 1964 New York World's Fair.",
  "Walt Disney World in Florida is nearly twice the size of Manhattan.",
  "Disney acquired Lucasfilm — and the Star Wars franchise — in 2012.",
  "Pixar's Toy Story (1995) was the first feature film ever made entirely with computer animation.",
  "The Haunted Mansion's lore claims it has 999 happy haunts, with room for one more.",
  "Beauty and the Beast's ballroom scene used an early 3D computer background, a first for Disney's hand-drawn animation.",
  "The Little Mermaid (1989) is often credited with kicking off the 'Disney Renaissance' era of animated films.",
  "Space Mountain first opened at Walt Disney World in 1975.",
  "The Lion King (1994) drew story inspiration from both Hamlet and African folklore.",
  "Frozen (2013) was loosely inspired by Hans Christian Andersen's fairy tale 'The Snow Queen.'",
  "EPCOT's full original name was 'Experimental Prototype Community of Tomorrow.'",
  "Magic Kingdom's Main Street U.S.A. was designed to evoke Walt Disney's hometown of Marceline, Missouri.",
  "Walt Disney pitched Disneyland to investors using little more than a hand-drawn map and pure conviction.",
  "Robin Williams reportedly improvised much of the Genie's dialogue in Aladdin (1992).",
  "'When You Wish Upon a Star' from Pinocchio won the Academy Award for Best Original Song in 1940 and became Disney's signature theme.",
  "Cinderella Castle contains a hidden suite that was originally intended for the Disney family.",
  "Zootopia (2016) won the Academy Award for Best Animated Feature.",
  "The Jungle Book (1967) was the last animated film Walt Disney personally worked on before his death.",
  "Pixar's Luxo Jr. lamp, from the studio's opening logo, starred in Pixar's first Oscar-nominated short film in 1986.",
  "Tokyo Disneyland, opened in 1983, was the first Disney park built outside the United States.",
  "Moana's animators built an entirely new water-simulation system to bring the ocean itself to life as a character.",
  "Steamboat Willie (1928) was the first cartoon with synchronized sound, and it introduced Mickey Mouse to the world.",
  "Fantasia (1940) paired classical music with animation and was among the earliest films released in stereophonic sound.",
  "Mulan (1998) was inspired by the Chinese legend of Hua Mulan, a woman who took her father's place in the army.",
  "Walt Disney set Disneyland's Main Street shop windows at a child's eye level on purpose, for a more nostalgic feel.",
  "The name 'Pixar' blends a nod to 'pixel' with a Spanish-style suffix meaning something like a laser-ray.",
  "Beauty and the Beast (1991) was the first animated film ever nominated for the Academy Award for Best Picture.",
  "The Matterhorn Bobsleds, opened in 1959, was the world's first tubular steel roller coaster.",
  "Sleeping Beauty (1959) took nearly six years to complete and was animated in a wide, storybook-style format.",
  "Robin Hood (1973) reused animation footage from earlier films, including The Jungle Book, to save on production costs.",
  "EPCOT's iconic 'ball,' Spaceship Earth, is technically a geodesic sphere, not a true dome.",
  "Up's opening montage of Carl and Ellie's life together is often cited as one of the most emotional sequences in animated film.",
  "The Aristocats (1970) was the last film personally approved by Walt Disney before he passed away in 1966.",
  "Coco (2017) was widely praised for its respectful portrayal of Mexican culture and the tradition of Día de los Muertos.",
  "Walt Disney sketched an early version of Mickey Mouse on a train ride home after losing the rights to a previous character, Oswald the Lucky Rabbit.",
  "Wreck-It Ralph (2012) features cameos from real classic arcade characters, including Pac-Man's ghosts.",
  "Pocahontas (1995) was the first Disney animated film based on a real historical figure.",
  "The Twilight Zone Tower of Terror was Disney's first major attraction based on outside intellectual property.",
  "Toy Story 2 was almost entirely lost to a computer error during production — it was saved because an employee had a backup copy at home.",
  "Big Thunder Mountain Railroad is themed as 'the wildest ride in the wilderness,' inspired by the American Southwest.",
  "Encanto's magical house, Casita, was designed by the filmmakers to feel like a character in its own right.",
  "The Sword in the Stone (1963) was one of Disney's earliest films to use xerography, cutting down on hand-inking animation cells.",
  "Frozen's 'Let It Go' won the Academy Award for Best Original Song in 2014.",
  "Disneyland's Club 33 is a private, members-only restaurant hidden within New Orleans Square.",
  "Animators studied real fawns brought into the studio to help bring Bambi (1942) to life.",
  "The Incredibles (2004) was Pixar's first film built around a primarily human cast of characters.",
  "Walt Disney's company got its start as the 'Laugh-O-Gram Studio' in Kansas City, before it went bankrupt.",
  "Inside Out (2015) worked with psychologists to help ground its story in real human emotion.",
  "The Country Bear Jamboree was one of the last attractions Walt Disney worked on before he passed away.",
  "Peter Pan (1953) was inspired by J.M. Barrie's original stage play, first performed in 1904.",
  "Soul (2020) was Pixar's first film to feature a Black lead character.",
  "Disney California Adventure was built on what used to be Disneyland's original parking lot.",
  "Lady and the Tramp (1955) was the first animated feature filmed in widescreen CinemaScope.",
  "Tangled's animators built new hair-simulation software just to bring Rapunzel's incredibly long hair to life.",
  "Disney's 'Imagineers' — the designers behind theme park attractions — get their name from blending 'imagination' and 'engineering.'",
  "WALL-E (2008) has almost no dialogue in its first 30 minutes, telling the story visually instead.",
  "Brave (2012) was Pixar's first film with a female protagonist, and it won the Academy Award for Best Animated Feature.",
  "Walt Disney's original EPCOT concept imagined an actual functioning city of the future, not a theme park.",
  "The Pirates of the Caribbean ride came first — the blockbuster movie franchise was inspired by the attraction, not the other way around.",
  "Finding Nemo (2003) was, for years, the best-selling DVD of all time.",
  "'A Whole New World' from Aladdin won both the Academy Award and the Grammy for Best Original Song.",
  "Monsters, Inc. (2001) was Pixar's first film to build an entirely fictional world with its own rules and society.",
  "Cinderella (1950) was a major financial turning point for Disney, helping the studio recover after a string of box-office underperformers.",
  "Hercules drew visual inspiration from ancient Greek pottery art for parts of its animation style.",
  "The 'Disney Villains' have their own dedicated merchandise line, with Maleficent from Sleeping Beauty as a longtime fan favorite.",
  "Ratatouille's animators consulted real chefs to make the film's cooking scenes feel authentic.",
  "Walt Disney's very first cartoon studio venture was in Kansas City, years before he ever set foot in California.",
  "The song score for The Jungle Book (1967) featured jazz legend Louis Prima as the voice — and singing style — of King Louie.",
];

// One {q, a} pair per HEALTH_FACTS / DISNEY_FACTS entry, same index order, used
// by the Daily Guess game so it asks a real question instead of echoing the fact.
const HEALTH_QUESTIONS = [
  { q: "About how many nerve endings does the clitoris have?", a: "8,000+" },
  { q: "Which heart attack symptoms are more common in women than men?", a: "Nausea, jaw pain, fatigue" },
  { q: "On average, how long does it take to diagnose endometriosis?", a: "7-10 years" },
  { q: "What was the first FDA-approved birth control pill called?", a: "Enovid" },
  { q: "Who was the first woman to earn a medical degree in the U.S.?", a: "Elizabeth Blackwell" },
  { q: "About how much can the uterus's surface area grow during pregnancy?", a: "Nearly double (fist to watermelon size)" },
  { q: "Why does alcohol tend to hit women harder per drink than men?", a: "Lower alcohol dehydrogenase levels" },
  { q: "What's the healthy range for menstrual cycle length?", a: "21-35 days" },
  { q: "What condition affects up to 1 in 10 women and is a leading cause of infertility?", a: "PCOS" },
  { q: "How much more common is osteoporosis in women than men?", a: "About 4x more common" },
  { q: "How effective is the HPV vaccine at preventing HPV-related cancers?", a: "Over 90%" },
  { q: "How much more often are autoimmune diseases like lupus diagnosed in women?", a: "About 4x more often" },
  { q: "About how many new mothers experience postpartum depression?", a: "1 in 7" },
  { q: "What's notable about the uterus's muscle strength?", a: "Strongest muscle in the body, relative to size" },
  { q: "How much more common are migraines in women than men?", a: "About 3x more common" },
  { q: "Who was the first Black woman to earn an M.D. in the U.S.?", a: "Rebecca Lee Crumpler" },
  { q: "When did the NIH start requiring female participants in clinical trials?", a: "1993" },
  { q: "About how many tampons or pads does a person use in their lifetime?", a: "About 11,000" },
  { q: "What percentage of pregnancies are affected by preeclampsia?", a: "5-8%" },
  { q: "How much more likely are women to be diagnosed with depression than men?", a: "About twice as likely" },
  { q: "What changes throughout the cycle that fertility awareness methods track?", a: "Cervix position and firmness" },
  { q: "Until about what age does breast tissue continue developing?", a: "Age 25" },
  { q: "How often should tampons be changed to reduce toxic shock syndrome risk?", a: "Every 4-8 hours" },
  { q: "When did the WHO classify infertility as a disease?", a: "2009" },
  { q: "Why does heart disease risk rise sharply after menopause?", a: "Drop in protective estrogen" },
  { q: "What percentage of U.S. pregnancies are affected by gestational diabetes?", a: "2-10%" },
  { q: "What's an effective treatment for postpartum incontinence?", a: "Pelvic floor physical therapy" },
  { q: "About how many eggs are present in the ovaries at birth?", a: "1-2 million" },
  { q: "Why is iron-deficiency anemia more common in women?", a: "Menstrual blood loss" },
  { q: "What language does 'hysteria' come from, and what did it mean?", a: "Greek, meaning uterus" },
  { q: "What percentage of women have fibroids by age 50?", a: "Up to 80%" },
  { q: "What hormone does breastfeeding trigger that helps shrink the uterus?", a: "Oxytocin" },
  { q: "How much more often is autoimmune thyroid disease diagnosed in women?", a: "5-8x more often" },
  { q: "Who invented the APGAR score for assessing newborn health?", a: "Dr. Virginia Apgar" },
  { q: "What is the normal pH range of the vagina?", a: "3.8-4.5 (acidic)" },
  { q: "About how many women experience chronic pelvic pain?", a: "1 in 7" },
  { q: "What hormone causes body temperature to rise after ovulation?", a: "Progesterone" },
  { q: "Who developed the first cervical cancer screening (Pap smear)?", a: "Dr. Georgios Papanikolaou" },
  { q: "How long can perimenopause last?", a: "A few months to over a decade" },
  { q: "Why are women often underdiagnosed for ADHD?", a: "Symptoms present as inattentiveness, not hyperactivity" },
  { q: "What's the failure rate of an IUD?", a: "Less than 1%" },
  { q: "How does a first-degree relative's breast cancer affect your own risk?", a: "Roughly doubles it" },
  { q: "What's the most common vaginal condition in women of reproductive age?", a: "Bacterial vaginosis" },
  { q: "What pregnancy complication has become more common as C-section rates rise?", a: "Placenta accreta" },
  { q: "How long is the luteal phase of the menstrual cycle?", a: "About 12-14 days" },
  { q: "About what percentage of women experience vulvodynia at some point?", a: "8-16%" },
  { q: "What hormone level is used to estimate ovarian reserve?", a: "Anti-Müllerian hormone (AMH)" },
  { q: "What's a documented pattern about women's pain in emergency rooms?", a: "More likely to be dismissed or under-treated" },
  { q: "Do breast development and pubic hair growth always start together?", a: "No, they don't always align" },
  { q: "What 1970s IUD scandal led to major contraceptive device reforms?", a: "The Dalkon Shield scandal" },
  { q: "About how many women will experience a miscarriage at some point?", a: "1 in 4" },
  { q: "What three things does the 'female athlete triad' link together?", a: "Low energy, menstrual dysfunction, low bone density" },
  { q: "How does cervical mucus change near ovulation?", a: "Becomes a fertile 'egg white' consistency" },
  { q: "What condition is often confused with fibroids and causes heavy, painful periods?", a: "Uterine adenomyosis" },
  { q: "How much more likely are women to develop IBS than men?", a: "About twice as likely" },
  { q: "What organization tracks reproductive health policy and research?", a: "The Guttmacher Institute" },
  { q: "What hormone can suppress ovulation during breastfeeding?", a: "Prolactin" },
  { q: "What kind of vaginal flora is linked to lower infection risk?", a: "Lactobacillus-dominant flora" },
  { q: "What was historically excluded from 'default' anatomy textbook diagrams?", a: "The female reproductive system" },
  { q: "What can chronic stress disrupt, sometimes causing missed periods?", a: "The hypothalamic-pituitary-ovarian axis" },
  { q: "What 1920s program helped cut maternal mortality in rural Appalachia?", a: "The Frontier Nursing Service" },
  { q: "What surgical emergency happens when an ovary twists on its ligaments?", a: "Ovarian torsion" },
  { q: "Is the placebo pill week in birth control medically necessary?", a: "No — mostly historical/cultural" },
  { q: "Why do women tend to be shorter than men on average?", a: "Bones finish growing earlier" },
  { q: "What chronic bladder condition affects women far more than men?", a: "Interstitial cystitis" },
  { q: "What is the first milk after birth often nicknamed?", a: "A baby's 'first vaccine'" },
  { q: "What's the postpartum period sometimes called?", a: "The 'fourth trimester'" },
  { q: "What protective effect does estrogen have on the body?", a: "Cardiovascular protection" },
  { q: "About how common is Turner syndrome in female births?", a: "1 in 2,000-2,500" },
  { q: "What does the term 'bikini medicine' criticize?", a: "Research stopping at reproductive organs only" },
  { q: "What's screened for late in pregnancy to prevent a serious newborn infection?", a: "Group B Streptococcus" },
  { q: "Why are women more likely to experience adverse drug reactions?", a: "Underrepresentation in dosing trials" },
  { q: "What's the average age of menopause in the U.S.?", a: "51" },
  { q: "What's it called when a fertilized egg implants outside the uterus?", a: "Ectopic pregnancy" },
  { q: "What's the medical term for painful periods?", a: "Dysmenorrhea" },
  { q: "What long-running study, started in 1976, investigates women's health risks?", a: "The Nurses' Health Study" },
  { q: "About what percentage of women get hot flashes during menopause?", a: "Up to 80%" },
  { q: "About how common is a retroverted ('tilted') uterus?", a: "About 1 in 5 women" },
  { q: "What's a leading, often preventable cause of maternal mortality?", a: "Postpartum hemorrhage" },
  { q: "What's monitored in high-risk pregnancies to predict preterm birth?", a: "Cervical length" },
  { q: "What's the 'sandwich generation' effect?", a: "Caring for kids and aging parents at once" },
  { q: "When does estrogen typically peak in the menstrual cycle?", a: "At ovulation" },
  { q: "What congenital condition is a common cause of recurrent miscarriage?", a: "Uterine septum" },
  { q: "How much more often is MS diagnosed in women than men?", a: "2-3x more often" },
  { q: "Who are Kegel exercises named after?", a: "Dr. Arnold Kegel" },
  { q: "How does the U.S. maternal mortality rate compare to other wealthy countries?", a: "Higher, with stark racial disparities" },
  { q: "Can you get a period-like bleed without ovulating?", a: "Yes — an anovulatory cycle" },
  { q: "What's the severe form of PMS called?", a: "PMDD" },
  { q: "What does the 'gender pain gap' describe?", a: "Women's pain taken less seriously by clinicians" },
  { q: "What's linked to shorter labors and lower C-section rates?", a: "Doula support" },
  { q: "What rare complication involves abnormal tissue instead of a viable embryo?", a: "Molar pregnancy" },
  { q: "Why does basal body temperature tracking work for fertility awareness?", a: "Progesterone raises temperature after ovulation" },
  { q: "What can frequent yeast infections (4+/year) sometimes point to?", a: "An underlying condition like diabetes" },
  { q: "What does the 'weathering hypothesis' link to worse maternal outcomes for Black women?", a: "Chronic stress from systemic racism" },
  { q: "Do most ovarian cysts require treatment?", a: "No — they usually resolve on their own" },
  { q: "What minimally invasive fibroid treatment emerged in the 1990s?", a: "Uterine fibroid embolization" },
  { q: "Why are some medications dosed differently for women?", a: "Slower metabolism from liver enzyme differences" },
  { q: "Where and when was the first PA program founded?", a: "Duke University, 1965" },
  { q: "What pregnancy complication involves the placenta covering the cervix?", a: "Placenta previa" },
  { q: "Since what year has egg-freezing technology advanced rapidly?", a: "1986 (first successful frozen-egg birth)" },
  { q: "When are women more likely to be hospitalized for autoimmune flares?", a: "Postpartum and perimenopause" },
  { q: "What's the 'orgasm gap' partly tied to?", a: "Gaps in anatomical education" },
  { q: "How long can periods be absent before it warrants a medical workup?", a: "3+ months" },
  { q: "About how many women who've given birth experience some uterine prolapse?", a: "Up to half" },
  { q: "Who was the first person born via IVF?", a: "Louise Brown, 1978" },
  { q: "What do sex hormones influence that's tied to more autoimmune risk in women?", a: "Immune response strength" },
  { q: "What nutrient reduces neural tube defect risk before conception?", a: "Folate" },
  { q: "About how long is the average PA program?", a: "27 months" },
];

const DISNEY_QUESTIONS = [
  { q: "What was Walt Disney afraid of in real life, despite creating Mickey Mouse?", a: "Mice" },
  { q: "What was Mickey Mouse almost named instead?", a: "Mortimer" },
  { q: "What was the first full-length hand-drawn animated feature film?", a: "Snow White and the Seven Dwarfs (1937)" },
  { q: "How many competitive Academy Awards did Walt Disney win in his lifetime?", a: "22" },
  { q: "When did Disneyland in Anaheim open?", a: "July 17, 1955" },
  { q: "Which castle is actually shorter: Cinderella Castle or Sleeping Beauty Castle?", a: "Cinderella Castle" },
  { q: "Who voiced Mickey Mouse from 1928 to 1947?", a: "Walt Disney himself" },
  { q: "What event was 'It's a Small World' originally created for?", a: "The 1964 New York World's Fair" },
  { q: "How does Walt Disney World's size compare to Manhattan?", a: "Nearly twice the size" },
  { q: "When did Disney acquire Lucasfilm and Star Wars?", a: "2012" },
  { q: "What was the first feature film made entirely with computer animation?", a: "Toy Story (1995)" },
  { q: "How many 'happy haunts' does the Haunted Mansion claim room for?", a: "999 (with room for one more)" },
  { q: "What animation first did Beauty and the Beast's ballroom scene use?", a: "An early 3D computer background" },
  { q: "What film is credited with starting the 'Disney Renaissance'?", a: "The Little Mermaid (1989)" },
  { q: "When did Space Mountain first open at Walt Disney World?", a: "1975" },
  { q: "What Shakespeare play inspired The Lion King's story?", a: "Hamlet" },
  { q: "What fairy tale loosely inspired Frozen?", a: "'The Snow Queen' by Hans Christian Andersen" },
  { q: "What does EPCOT originally stand for?", a: "Experimental Prototype Community of Tomorrow" },
  { q: "What hometown inspired Magic Kingdom's Main Street U.S.A.?", a: "Marceline, Missouri" },
  { q: "How did Walt Disney pitch Disneyland to investors?", a: "With a hand-drawn map and conviction" },
  { q: "Who reportedly improvised much of the Genie's dialogue in Aladdin?", a: "Robin Williams" },
  { q: "What song won Disney's first Best Original Song Oscar, from Pinocchio?", a: "'When You Wish Upon a Star'" },
  { q: "What's hidden inside Cinderella Castle?", a: "A suite originally meant for the Disney family" },
  { q: "What film won Best Animated Feature in 2016?", a: "Zootopia" },
  { q: "What was the last animated film Walt Disney personally worked on?", a: "The Jungle Book (1967)" },
  { q: "What lamp stars in Pixar's opening logo?", a: "Luxo Jr." },
  { q: "What was the first Disney park built outside the U.S.?", a: "Tokyo Disneyland (1983)" },
  { q: "What new technology did Moana's animators build for the ocean?", a: "A new water-simulation system" },
  { q: "What was the first cartoon with synchronized sound?", a: "Steamboat Willie (1928)" },
  { q: "What Disney film paired classical music with animation in 1940?", a: "Fantasia" },
  { q: "What Chinese legend inspired Mulan?", a: "Hua Mulan" },
  { q: "Why did Walt Disney set Main Street's shop windows lower?", a: "To feel more nostalgic, at a child's eye level" },
  { q: "Where does the name 'Pixar' come from?", a: "A blend of 'pixel' and a laser-ray-style suffix" },
  { q: "What was the first animated film nominated for Best Picture?", a: "Beauty and the Beast (1991)" },
  { q: "What was the world's first tubular steel roller coaster?", a: "The Matterhorn Bobsleds" },
  { q: "About how long did Sleeping Beauty (1959) take to complete?", a: "Nearly six years" },
  { q: "What Disney film reused animation footage from The Jungle Book to save costs?", a: "Robin Hood (1973)" },
  { q: "What shape is EPCOT's Spaceship Earth, technically?", a: "A geodesic sphere, not a dome" },
  { q: "What's often cited as one of the most emotional sequences in animated film?", a: "Up's opening montage of Carl and Ellie" },
  { q: "What was the last film Walt Disney personally approved before his death?", a: "The Aristocats (1970)" },
  { q: "What film was praised for its portrayal of Día de los Muertos?", a: "Coco (2017)" },
  { q: "Where did Walt Disney sketch an early version of Mickey Mouse?", a: "On a train ride home" },
  { q: "What classic arcade characters cameo in Wreck-It Ralph?", a: "Pac-Man's ghosts" },
  { q: "What was the first Disney animated film based on a real historical figure?", a: "Pocahontas (1995)" },
  { q: "What was Disney's first major attraction based on outside intellectual property?", a: "The Twilight Zone Tower of Terror" },
  { q: "What almost destroyed Toy Story 2 during production?", a: "A computer error (saved by an employee's backup)" },
  { q: "What is Big Thunder Mountain Railroad themed as?", a: "'The wildest ride in the wilderness'" },
  { q: "What's the name of the magical house in Encanto?", a: "Casita" },
  { q: "What technology did The Sword in the Stone (1963) help popularize?", a: "Xerography" },
  { q: "What song from Frozen won the 2014 Best Original Song Oscar?", a: "'Let It Go'" },
  { q: "What's the name of Disneyland's private, members-only restaurant?", a: "Club 33" },
  { q: "What did animators study to help bring Bambi to life?", a: "Real fawns brought into the studio" },
  { q: "What was Pixar's first film with a primarily human cast?", a: "The Incredibles (2004)" },
  { q: "What was the name of Walt Disney's first studio, in Kansas City?", a: "Laugh-O-Gram Studio" },
  { q: "Who did Inside Out work with to ground its story in real emotion?", a: "Psychologists" },
  { q: "What was one of the last attractions Walt Disney worked on?", a: "The Country Bear Jamboree" },
  { q: "What year was J.M. Barrie's original Peter Pan stage play first performed?", a: "1904" },
  { q: "What was Pixar's first film with a Black lead character?", a: "Soul (2020)" },
  { q: "What used to occupy the site of Disney California Adventure?", a: "Disneyland's original parking lot" },
  { q: "What was the first animated feature filmed in widescreen CinemaScope?", a: "Lady and the Tramp (1955)" },
  { q: "What new software did Tangled's animators build for Rapunzel's hair?", a: "Hair-simulation software" },
  { q: "Where does the term 'Imagineers' come from?", a: "Blending 'imagination' and 'engineering'" },
  { q: "How much dialogue does WALL-E have in its first 30 minutes?", a: "Almost none" },
  { q: "What was Pixar's first film with a female protagonist?", a: "Brave (2012)" },
  { q: "What did Walt Disney's original EPCOT concept imagine?", a: "An actual functioning city of the future" },
  { q: "Which came first: the Pirates of the Caribbean ride or the movie franchise?", a: "The ride" },
  { q: "What was, for years, the best-selling DVD of all time?", a: "Finding Nemo (2003)" },
  { q: "What Aladdin song won both an Oscar and a Grammy?", a: "'A Whole New World'" },
  { q: "What was Pixar's first film to build an entirely fictional world?", a: "Monsters, Inc. (2001)" },
  { q: "What film was a major financial turning point for Disney in 1950?", a: "Cinderella" },
  { q: "What art style inspired parts of Hercules' animation?", a: "Ancient Greek pottery art" },
  { q: "Which classic villain is a longtime fan favorite from Sleeping Beauty?", a: "Maleficent" },
  { q: "Who did Ratatouille's animators consult for the cooking scenes?", a: "Real chefs" },
  { q: "Where was Walt Disney's very first cartoon studio venture located?", a: "Kansas City" },
  { q: "Who voiced King Louie in The Jungle Book (1967)?", a: "Louis Prima" },
];

function factForDate(list, date) {
  const start = new Date(date.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((date - start) / 86400000);
  return list[dayOfYear % list.length];
}
